export const GET_SUBSCRIBES = 'SUBSCRIBES/GET_SUBSCRIBES';
export const PAGE_NUMBER = 'SUBSCRIBES/PAGE_NUMBER';
export const PAGE_SIZE = 'SUBSCRIBES/PAGE_SIZE';
export const SUBSCRIBES_COUNT = 'SUBSCRIBES/SUBSCRIBES_COUNT';
export const PER_PAGE = 'SUBSCRIBES/PER_PAGE';
