
export const SUCCESSFUL_AUTHENTICATION = 'USER/SUCCESSFUL_AUTHENTICATION';
export const CLEAR_AUTHENTICATION = 'USER/CLEAR_AUTHENTICATION';
export const TRIED_REFRESH_AUTHENTICATION = 'USER/TRIED_REFRESH_AUTHENTICATION';
export const SET_AUTHENTICATION_USER = 'USER/SET_AUTHENTICATION_USER';
export const ENABLED_TFA_AUTHENTICATION = 'USER/ENABLED_TFA_AUTHENTICATION';
export const DISABLED_TFA_AUTHENTICATION = 'USER/DISABLED_TFA_AUTHENTICATION';
export const SET_TFA_QR_CODE = 'USER/SET_TFA_QR_CODE';

export const CLEAR_PASSWORD_FORM = 'USER/CLEAR_PASSWORD_FORM';
export const SHOW_PASSWORD_FORM = 'USER/SHOW_PASSWORD_FORM';
export const HIDE_PASSWORD_FORM = 'USER/HIDE_PASSWORD_FORM';
export const SHOW_EMAIL_FORM = 'USER/SHOW_EMAIL_FORM';
export const HIDE_EMAIL_FORM = 'USER/HIDE_EMAIL_FORM';
export const SET_PASSWORD_FORM_FIELD = 'USER/SET_PASSWORD_FORM_FIELD';
export const SET_EMAIL_FORM_FIELD = 'USER/SET_EMAIL_FORM_FIELD';
export const ENABLED_PASSWORD_FORM_FIELD_ERROR = 'USER/ENABLED_PASSWORD_FORM_FIELD_ERROR';
export const DISABLED_PASSWORD_FORM_FIELD_ERROR = 'USER/DISABLED_PASSWORD_FORM_FIELD_ERROR';
export const ENABLED_EMAIL_FORM_FIELD_ERROR = 'USER/ENABLED_EMAIL_FORM_FIELD_ERROR';
export const DISABLED_EMAIL_FORM_FIELD_ERROR = 'USER/DISABLED_EMAIL_FORM_FIELD_ERROR';
export const DISABLED_PASSWORD_FORM_ERRORS = 'USER/DISABLED_PASSWORD_FORM_ERRORS';
export const DISABLED_EMAIL_FORM_ERRORS = 'USER/DISABLED_EMAIL_FORM_ERRORS';
